### ISSUE TITLE
Cleanup name of generated javascript file and function

### ISSUE THREAD

**Issue by mephinet** [necinc/msvgc#2]
Minor issue: if the filename of the input SVG is not a valid javascript name (e.g. because it contains dashes), the generated js is invalid:

```
const abc-def-ghi = props => (
...
)
```

**Comment by thurt** [comment]
i encountered this issue as well. 

file naming with dashes is pretty common with graphic assets.

seems like it would make sense to convert this to camelCase.

**Comment by TheTekton** [comment]
This [fork](https://github.com/TheTekton/msvgc/tree/development) has commits in the development branch that adds support for --camelCase. It also has support for subdirectories in the svg directory, and a component index.js is written to the component output root.

Not sure if it's PR-worthy, but can start one for review, if @necinc asks.

**Comment by maximalism2** [comment]
@TheTekton that's great idea! Could you please create the PR, and we will continue the conversation there?

**Comment by maximalism2** [comment]
Resolved in #4
